### ISSUE TITLE
RULES for Hue lights

### ISSUE THREAD

**Issue by Stifler6996** [lamiastella/OpenHAB#1]
You don't realistically need rules for lights, unless you are doing something fancy.

Simply Use the Type Switch for on/off.
Use Type Dimmer for dimming lights, and use Type Colorpicker for selecting colours.

You on/off rule is also creating an infinite loop. Once triggered, expect the unexpected!

Regards.

**Comment by lamiastella** [comment]
Thank you, I have noted your help here http://stackoverflow.com/questions/36167273/the-ui-cant-control-the-philips-hue-color-lightbulb
